apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vinay-golkonda99/MLOps-Project.git
    targetRevision: main
    path: K8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlapp             # You can choose your desired namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
