apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-app
  labels:
    app: llm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm-container
          image: vinaygolkonda99/llm_deps:llm_app
          ports:
            - name: http                # ✅ Added for Prometheus PodMonitor
              containerPort: 1999      # App + /metrics runs here
          env:
            - name: MODEL_PATH
              value: /mnt/models/Deepseek
