# Builder Stage
FROM python:3.10.11-slim-buster as builder

WORKDIR /build

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc build-essential libffi-dev libssl-dev libxml2-dev libxslt1-dev \
    wget unzip && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip --no-cache-dir install --upgrade pip setuptools==67.4.0 wheel==0.38.4 && \
    pip --no-cache-dir install --target=/python-deps -r requirements.txt

WORKDIR /opt/oracle

RUN wget https://download.oracle.com/otn_software/linux/instantclient/1918000/instantclient-basiclite-linux.x64-19.18.0.0.0dbru.zip && \
    unzip instantclient-basiclite-linux.x64-19.18.0.0.0dbru.zip && \
    rm -f instantclient-basiclite-linux.x64-19.18.0.0.0dbru.zip

RUN cd /opt/oracle/instantclient_19_18 && \
    rm -f jdbc occi mysql *README *jar uidrvci generzi adrci

RUN echo /opt/oracle/instantclient_19_18 > /etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig


# Model Builder Stage
FROM python:3.10.11-slim-buster AS model_builder

RUN pip install --no-cache-dir huggingface_hub nltk

# Download NLTK data and model from Huggingface repo
RUN python -m nltk.downloader punkt stopwords wordnet

RUN python -c "from huggingface_hub import snapshot_download;snapshot_download(repo_id='BEE-spoke-data/smol_llama-101M-GQA',local_dir='/mnt/models/Deepseek',local_dir_use_symlinks=False)"


# OpenJDK 19 builder stage
FROM debian:bullseye-slim AS openjdk17_builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jdk-headless && \
    rm -rf /var/lib/apt/lists/*


# Final Runtime Stage
FROM python:3.10.11-slim-buster

WORKDIR /app

RUN mkdir -p /var/log/containers

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libaio1 \
        wget \
        dpkg=1.19.8 \
        gzip \
        unzip \
        nginx && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/oracle /opt/oracle
COPY --from=builder /etc/ld.so.conf.d/oracle-instantclient.conf /etc/ld.so.conf.d/oracle-instantclient.conf
RUN ldconfig

COPY --from=builder /python-deps /usr/local/lib/python3.10/site-packages

# Copy models and nltk data from model_builder stage
COPY --from=model_builder /mnt/models/Deepseek /mnt/models/Deepseek
COPY --from=model_builder /root/nltk_data /root/nltk_data

COPY --from=openjdk17_builder /usr/lib/jvm/java-17-openjdk-amd64 /usr/lib/jvm/java-17-openjdk-amd64

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_19_18:$LD_LIBRARY_PATH
ENV PATH=/opt/oracle/instantclient_19_18:$PATH
ENV PYTHONPATH=/usr/local/lib/python3.10/site-packages
ENV NLTK_DATA=/root/nltk_data
ENV MODEL_PATH=/mnt/models/Deepseek

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

