apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: llm-app-monitor
  namespace: monitoring
  labels:
    release: mimir
spec:
  selector:
    matchLabels:
      app: llm       # Match your deployment
  namespaceSelector:
    matchNames:
      - default       # or whatever namespace you're using
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
